[package]
name = "cbmix_admin_proto"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }
