rust_library(
    name = "cbmix_graph",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//cbmix_common:cbmix_common",
        "//third-party:generational-arena",
        "//third-party:ola",
        "//third-party:petgraph",
        "//third-party:thiserror",
        "//third-party:tokio",
        "//third-party:tracing",
        "//third-party:uuid",
    ],
    visibility = ["PUBLIC"],
)
